services:
  surrealstarter:
    build: .
    container_name: surrealstarter
    restart: always
    networks:
      - web
    expose:
      - "3631"

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - web
    depends_on:
      - surrealstarter

networks:
  web:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
